// Pure builder for the locally-constructed Case Note. Kept separate from
// `useLogCallReconciler` so the build step is testable without React and so
// the reconciler hook is a thin orchestrator over composable pieces.
//
// The `optimisticId` is generated by the caller (the reconciler hook owns
// the lifecycle). We accept a `now` function for the same reason —
// deterministic tests.

import type { LogCallStatus, LogCallType } from "@anthos/api";

import type { OptimisticCaseNote } from "./types";

export interface BuildOptimisticInput {
  readonly participantId: string;
  readonly optimisticId: string;
  readonly callStatus: LogCallStatus;
  readonly type: LogCallType;
  readonly serviceDate: string;
  readonly summary: string | null;
  readonly now: () => Date;
}

export function buildOptimisticCaseNote(
  input: BuildOptimisticInput,
): OptimisticCaseNote {
  return {
    optimisticId: input.optimisticId,
    participantId: input.participantId,
    callStatus: input.callStatus,
    type: input.type,
    serviceDate: input.serviceDate,
    summary: input.summary,
    optimisticAt: input.now().toISOString(),
  };
}
