-- Reverse of 0011_enable_rls_public_tables.sql.
ALTER TABLE "audit_log" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "caseload_cache" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "cdc_health" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "configuration" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "configuration_audit" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "idempotency_keys" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "notification_preferences" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "offline_queue" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "rate_limits" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "sessions" DISABLE ROW LEVEL SECURITY;
